'use client';

import { useState } from 'react';
import { DISTRICTS, CPO_SERIES } from '@/lib/data';
import RiauMap from '@/components/riau-map';
import RecommendationCards from '@/components/cards';
import PriceChart from '@/components/chart';

const MAP_TABS = ['Crop health', 'Weather', 'Yield forecast'] as const;
const CHART_TABS = ['4w', '8w', '26w', '52w'] as const;

export default function OverviewPage() {
  const [selected, setSelected] = useState('kampar');
  const [mapTab, setMapTab] = useState<(typeof MAP_TABS)[number]>('Crop health');
  const [chartTab, setChartTab] = useState<(typeof CHART_TABS)[number]>('8w');

  const counts = DISTRICTS.reduce<Record<string, number>>((acc, d) => {
    acc[d.status] = (acc[d.status] || 0) + 1;
    return acc;
  }, {});

  const current = CPO_SERIES[CPO_SERIES.length - 1];

  return (
    <>
      <div className="topbar">
        <div>
          <div className="crumb">Riau Province · Week 17 · Apr 15 – Apr 21, 2026</div>
          <h1 className="page-title">Procurement overview</h1>
          <div className="page-sub">Dispatch decisions for 5 kecamatan · last sync 14 minutes ago</div>
        </div>
        <div className="topbar-actions">
          <button className="btn">
            <svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5">
              <path d="M3 4 L13 4 M3 8 L13 8 M3 12 L13 12" />
            </svg>
            Filter
          </button>
          <button className="btn">
            <svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round">
              <path d="M8 2 L8 11 M8 11 L4.5 7.5 M8 11 L11.5 7.5 M3 13.5 L13 13.5" />
            </svg>
            Export
          </button>
          <button className="btn primary">
            <span className="dot" />
            Dispatch plan · 13 trucks
          </button>
        </div>
      </div>

      <div className="kpi-row">
        <div className="kpi">
          <div className="label">Districts ready</div>
          <div className="val">
            {counts.green || 0}<span className="unit">of {DISTRICTS.length}</span>
          </div>
          <div className="delta up">▲ 1 vs last week</div>
        </div>
        <div className="kpi">
          <div className="label">Forecast intake</div>
          <div className="val mono">2,840<span className="unit">tonnes FFB</span></div>
          <div className="delta up">▲ 6.2% WoW</div>
        </div>
        <div className="kpi">
          <div className="label">CPO spot · Dumai</div>
          <div className="val mono">{current.price.toLocaleString('en-US')}<span className="unit">IDR/kg</span></div>
          <div className="delta up">▲ 0.6% · favorable</div>
        </div>
        <div className="kpi">
          <div className="label">Fleet utilization</div>
          <div className="val">78<span className="unit">%</span></div>
          <div className="delta flat">— stable</div>
        </div>
      </div>

      <section className="section">
        <div className="section-head">
          <div>
            <h2>Riau crop health · weekly assessment</h2>
            <div className="meta">Click a kecamatan to inspect · data from satellite NDVI + on-ground sampling</div>
          </div>
          <div className="right">
            <div className="tabs">
              {MAP_TABS.map((t) => (
                <div key={t} className={`tab${mapTab === t ? ' active' : ''}`} onClick={() => setMapTab(t)}>
                  {t}
                </div>
              ))}
            </div>
          </div>
        </div>
        <RiauMap selected={selected} setSelected={setSelected} />
      </section>

      <section className="section">
        <div className="section-head">
          <div>
            <h2>Weekly recommendations</h2>
            <div className="meta">Generated by Vela · scroll for all {DISTRICTS.length} districts</div>
          </div>
          <div className="right">
            <span className="badge green"><span className="dot" />{counts.green || 0} dispatch</span>
            <span className="badge amber"><span className="dot" />{counts.amber || 0} hold</span>
            <span className="badge red"><span className="dot" />{counts.red || 0} at risk</span>
          </div>
        </div>
        <RecommendationCards selected={selected} setSelected={setSelected} />
      </section>

      <section className="section">
        <div className="section-head">
          <div>
            <h2>CPO price trend · 8 weeks</h2>
            <div className="meta">Source: Bursa Malaysia Derivatives, Dumai port spot conversion</div>
          </div>
          <div className="right">
            <div className="tabs">
              {CHART_TABS.map((t) => (
                <div key={t} className={`tab${chartTab === t ? ' active' : ''}`} onClick={() => setChartTab(t)}>
                  {t}
                </div>
              ))}
            </div>
          </div>
        </div>
        <PriceChart />
        <div className="foot">
          <span>Updated Apr 21, 2026 · 14:38 WIB</span>
          <span>Next refresh in 22 min</span>
        </div>
      </section>
    </>
  );
}
