import type { CpoPoint, District, MapRegion } from '@/lib/dashboard-types';

export const DISTRICTS: District[] = [
  {
    id: 'kampar',
    name: 'Kampar',
    status: 'green',
    action: 'Dispatch now — peak yield window',
    cpo: 12400,
    cpoNote: 'favorable',
    ndvi: 0.74,
    yield: '4.2 t/ha',
    moisture: '21%',
    ffa: '2.1%',
    trucks: 6,
    eta: '14 hrs',
    confidence: 82,
  },
  {
    id: 'pelalawan',
    name: 'Pelalawan',
    status: 'amber',
    action: 'Hold this week — moisture rising',
    cpo: 12400,
    cpoNote: 'favorable',
    ndvi: 0.61,
    yield: '3.4 t/ha',
    moisture: '28%',
    ffa: '3.0%',
    trucks: 2,
    eta: '—',
    confidence: 61,
  },
  {
    id: 'inhu',
    name: 'Indragiri Hulu',
    status: 'red',
    action: 'Prioritize Kampar instead',
    cpo: 12400,
    cpoNote: 'favorable',
    ndvi: 0.43,
    yield: '2.1 t/ha',
    moisture: '34%',
    ffa: '4.6%',
    trucks: 0,
    eta: '—',
    confidence: 43,
  },
  {
    id: 'rohil',
    name: 'Rokan Hilir',
    status: 'green',
    action: 'Dispatch now — stable conditions',
    cpo: 12400,
    cpoNote: 'favorable',
    ndvi: 0.71,
    yield: '3.9 t/ha',
    moisture: '23%',
    ffa: '2.4%',
    trucks: 4,
    eta: '18 hrs',
    confidence: 71,
  },
  {
    id: 'siak',
    name: 'Siak',
    status: 'green',
    action: 'Dispatch — clear weather window',
    cpo: 12400,
    cpoNote: 'favorable',
    ndvi: 0.68,
    yield: '4.0 t/ha',
    moisture: '22%',
    ffa: '2.2%',
    trucks: 3,
    eta: '12 hrs',
    confidence: 68,
  },
];

export const CPO_SERIES: CpoPoint[] = [
  { week: 'Mar 03', price: 11820 },
  { week: 'Mar 10', price: 11950 },
  { week: 'Mar 17', price: 12080 },
  { week: 'Mar 24', price: 12010 },
  { week: 'Mar 31', price: 12130 },
  { week: 'Apr 07', price: 12270 },
  { week: 'Apr 14', price: 12310 },
  { week: 'Apr 21', price: 12400, current: true },
];

export const CPO_RECENT_BACKFILL_SERIES: CpoPoint[] = [
  { week: 'Apr 27', price: 15459, timestamp: '2026-04-27T07:00:00Z' },
  { week: 'Apr 29', price: 15220, timestamp: '2026-04-29T07:00:00Z' },
  { week: 'Apr 30', price: 15400, timestamp: '2026-04-30T07:00:00Z' },
  { week: 'May 04', price: 15400, timestamp: '2026-05-04T07:00:00Z' },
  { week: 'May 05', price: 15625, timestamp: '2026-05-05T07:00:00Z' },
  { week: 'May 06', price: 15575, timestamp: '2026-05-06T07:00:00Z', current: true },
];

export const MAP_REGIONS: MapRegion[] = [
  { id: 'bengkalis', name: 'Bengkalis', geoName: 'Bengkalis' },
  { id: 'dumai', name: 'Dumai', geoName: 'Kota Dumai' },
  { id: 'inhil', name: 'Indragiri Hilir', geoName: 'Indragiri Hilir' },
  { id: 'inhu', name: 'Indragiri Hulu', geoName: 'Indragiri Hulu' },
  { id: 'kampar', name: 'Kampar', geoName: 'Kampar' },
  { id: 'meranti', name: 'Kepulauan Meranti', geoName: 'Kepulauan Meranti' },
  { id: 'kuansing', name: 'Kuantan Singingi', geoName: 'Kuantan Singingi' },
  { id: 'pelalawan', name: 'Pelalawan', geoName: 'Pelalawan' },
  { id: 'pekanbaru', name: 'Pekanbaru', geoName: 'Kota Pekanbaru' },
  { id: 'rohil', name: 'Rokan Hilir', geoName: 'Rokan Hilir' },
  { id: 'rohul', name: 'Rokan Hulu', geoName: 'Rokan Hulu' },
  { id: 'siak', name: 'Siak', geoName: 'Siak' },
];

export const MILL = {
  name: 'PT Sawit Riau',
  location: 'Pekanbaru',
  fleetCount: 14,
};

export const USER = {
  name: 'Budi Santoso',
  initials: 'BS',
  role: 'Procurement lead',
};
